language: ruby
os: linux
sudo: false
cache: bundler

before_install:
  - HOMEBREW_REPOSITORY="$HOME/Homebrew"
  - export PATH="$HOMEBREW_REPOSITORY/bin:$PATH"
  # umask 022 fixes Linux `brew tests` failures
  - umask 022
  - rm -rf $HOMEBREW_REPOSITORY
  - travis_retry git clone --depth=1 https://github.com/Homebrew/brew "$HOMEBREW_REPOSITORY"
  - HOMEBREW_CORE_TAP_DIR="$HOMEBREW_REPOSITORY/Library/Taps/homebrew/homebrew-core"
  - mkdir -p "$HOMEBREW_CORE_TAP_DIR"
  - rm -rf "$HOMEBREW_CORE_TAP_DIR"
  - travis_retry git clone --depth=1 https://github.com/Homebrew/homebrew-core "$HOMEBREW_CORE_TAP_DIR"
  # trigger vendored ruby installation
  - brew help
  - bundle install
  - export HOMEBREW_NO_ANALYTICS=1

script:
  - bundle exec rake test
