# frozen_string_literal: true

source "https://rubygems.org"

ruby file: ".ruby-version"

gem "github-pages", group: :jekyll_plugins

group :test do
  gem "html-proofer"
  gem "mdl"
  gem "rake"
  gem "webrick"
end
